version: '3'

services:
  app:
    image: spaceonfire/nginx-php-fpm:latest-7.3
    environment:
      - SOF_PRESET=default
      - APPLICATION_ENV=test
      - WEBROOT=/dev/null
      - ENABLE_XDEBUG=1
      - XDEBUG_IDEKEY=apidoc
      - PAGER=more
      - PUID=1000
    volumes:
      - ./:/var/www/html
