<?php

use \spaceonfire\SimplePhpApiDoc\Renderers\Markdown\MarkdownHelper;

return [
    '',
    MarkdownHelper::hr(),
    '',
    'This file automatically generated by ' .
    MarkdownHelper::link('Simple PHP ApiDoc', 'https://github.com/spaceonfire/simple-php-apidoc'),
];
